when:
  - event: [tag]
    branch: master

labels:
  platform: linux/amd64
  target: serva

steps:
  - name: rclone-mount
    image: woodpeckerci/plugin-docker-buildx
    when:
      - evaluate: 'CI_COMMIT_TAG contains "rclone-"'
    settings:
      platforms: linux/amd64  # ,linux/arm64/v8
      dockerfile: rclone-mount/Dockerfile
      context: ./rclone-mount
      repo: ${CI_REPO_OWNER}/rclone-mount
      tags: latest,${CI_COMMIT_TAG}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: DOCKER_TOKEN
